[tool.poetry]
authors = [
  "Joel Lee <joel@joellee.org>",
  "Leon Fedden <leonfedden@gmail.com>",
  "Daniel Reinón García <danielreinon@outlook.com>",
  "Leynier Gutiérrez González <leynier41@gmail.com>",
  "Anand Krishna <anand2312@proton.me>"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
description = "Supabase Storage client for Python."
documentation = "https://supabase-community.github.io/storage-py"
homepage = "https://supabase-community.github.io/storage-py"
license = "MIT"
name = "storage3"
readme = "README.md"
repository = "https://github.com/supabase-community/storage-py"
version = "0.3.3"

[tool.poetry.dependencies]
httpx = ">=0.19,<0.22"
python = "^3.7"
typing-extensions = "^4.2.0"

[tool.poetry.dev-dependencies]
python-semantic-release = "^7.28.1"
black = "^22.3.0"
isort = "^5.9.3"
pre-commit = "^2.16.0"
pytest = "^6.2.5"
pytest-asyncio = "^0.18.3"
pytest-cov = "^3.0.0"
python-dotenv = "^0.20.0"
Sphinx = "^4.5.0"
sphinx-press-theme = "^0.8.0"
unasync-cli = "^0.0.9"

[tool.semantic_release]
version_variable = "storage3/utils.py:__version__"
version_toml = "pyproject.toml:tool.poetry.version"
major_on_zero = false
commit_subject = "chore(release): bump version to v{version}"
build_command = "curl -sSL https://install.python-poetry.org | python - --preview && export PATH=\"/github/home/.local/bin:$PATH\" && poetry install && poetry build"
upload_to_repository = true
branch = "main"
changelog_components = "semantic_release.changelog.changelog_headers,semantic_release.changelog.compare_url"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
